

import { UILanguage } from "../types";

type TranslationKey = 
  | 'app_title'
  | 'app_subtitle'
  | 'choose_topic_title'
  | 'choose_topic_desc'
  | 'long_speech_category'
  | 'dialogue_category'
  | 'favorites_title'
  | 'back_button'
  | 'no_favorites'
  | 'library_title'
  | 'library_desc'
  | 'generate_new_title'
  | 'generate_button'
  | 'downloaded_section'
  | 'no_files'
  | 'play_button'
  | 'pause_button'
  | 'resume_button'
  | 'vocab_test_btn'
  | 'vocab_test_desc'
  | 'key_vocab_title'
  | 'useful_phrases_title'
  | 'grammar_notes_title'
  | 'check_answers'
  | 'reset_quiz'
  | 'show_translations'
  | 'hide_translations'
  | 'comprehension_check'
  | 'explanation_label'
  | 'score_label'
  | 'test_select_mode'
  | 'test_back'
  | 'test_retry'
  | 'test_change_mode'
  | 'test_exit'
  | 'test_question'
  | 'test_score'
  | 'mode_kanji_hiragana'
  | 'mode_hiragana_kanji'
  | 'mode_hiragana_mm'
  | 'mode_kanji_mm'
  | 'test_result_perfect'
  | 'test_result_great'
  | 'test_result_good'
  | 'test_result_keep_practicing'
  | 'custom_topic_placeholder'
  | 'footer_text'
  | 'interview_field_label'
  | 'interview_custom_placeholder'
  | 'field_engineer'
  | 'field_kaigo'
  | 'field_it'
  | 'field_me'
  | 'field_ec'
  | 'field_ep'
  | 'field_design'
  | 'field_other'
  | 'toggle_furigana'
  | 'theme_sakura'
  | 'theme_fuji'
  | 'theme_jinjya'
  | 'theme_beach'
  | 'theme_sky'
  | 'theme_forest'
  | 'theme_magic'
  | 'theme_night'
  | 'theme_anime'
  | 'theme_demon_slayer'
  | 'theme_love'
  | 'theme_rain'
  | 'theme_three_d'
  | 'theme_fire'
  | 'theme_hanabi'
  | 'theme_winter'
  | 'theme_one_piece'
  | 'theme_galaxy'
  | 'voice_settings'
  | 'voice_speaker_a'
  | 'voice_speaker_b'
  | 'voice_speaker_c'
  | 'voice_narrator'
  | 'voice_male'
  | 'voice_female'
  | 'num_speakers'
  | 'speakers_1'
  | 'speakers_2'
  | 'speakers_3'
  | 'estimated_time'
  | 'seconds'
  | 'calculating'
  | 'voice_sharing_notice';

const TRANSLATIONS: Record<TranslationKey, Record<UILanguage, string>> = {
  app_title: {
    en: "Chōkai Master",
    jp: "聴解マスター",
    mm: "Chōkai Master"
  },
  app_subtitle: {
    en: "Advanced Japanese Listening",
    jp: "上級日本語聴解練習",
    mm: "အဆင့်မြင့် ဂျပန်စာ နားထောင်ခြင်း"
  },
  choose_topic_title: {
    en: "Choose Your Topic",
    jp: "トピックを選択",
    mm: "ခေါင်းစဉ်ရွေးချယ်ပါ"
  },
  choose_topic_desc: {
    en: "Select a category to start your advanced listening practice. Each session is uniquely generated by AI.",
    jp: "カテゴリーを選択して練習を開始してください。各セッションはAIによって生成されます。",
    mm: "လေ့ကျင့်မှုစတင်ရန် ခေါင်းစဉ်တစ်ခုရွေးပါ။ သင်ခန်းစာများကို AI ဖြင့် ဖန်တီးထားပါသည်။"
  },
  long_speech_category: {
    en: "Long Speech Practice (Monologue)",
    jp: "長文聴解 (モノローグ)",
    mm: "မိန့်ခွန်းရှည် လေ့ကျင့်ခန်း"
  },
  dialogue_category: {
    en: "Dialogue Practice",
    jp: "対話練習",
    mm: "အပြန်အလှန် စကားပြော လေ့ကျင့်ခန်း"
  },
  favorites_title: {
    en: "Favorites Notebook",
    jp: "単語帳",
    mm: "မှတ်ထားသော စာလုံးများ"
  },
  back_button: {
    en: "Back",
    jp: "戻る",
    mm: "ပြန်ထွက်"
  },
  no_favorites: {
    en: "No favorite words yet.",
    jp: "お気に入りの単語はまだありません。",
    mm: "မှတ်သားထားသော စာလုံးမရှိသေးပါ။"
  },
  library_title: {
    en: "Library",
    jp: "ライブラリ",
    mm: "သိမ်းဆည်းထားမှုများ"
  },
  library_desc: {
    en: "Select a downloaded file or generate a new one.",
    jp: "保存されたファイルを選択するか、新しく生成してください。",
    mm: "ဒေါင်းလုဒ်လုပ်ထားသောဖိုင်ကို ရွေးပါ (သို့) အသစ်ပြုလုပ်ပါ။"
  },
  generate_new_title: {
    en: "Generate New Session",
    jp: "新しいセッションを生成",
    mm: "လေ့ကျင့်ခန်းအသစ် ပြုလုပ်မည်"
  },
  generate_button: {
    en: "Generate (AI)",
    jp: "AI生成する",
    mm: "AI ဖြင့်စတင်မည်"
  },
  downloaded_section: {
    en: "Downloaded Locally",
    jp: "ダウンロード済み",
    mm: "ဒေါင်းလုဒ်လုပ်ထားသော ဖိုင်များ"
  },
  no_files: {
    en: "No files downloaded yet.",
    jp: "ファイルはまだありません。",
    mm: "ဖိုင်မရှိသေးပါ။"
  },
  play_button: {
    en: "Play",
    jp: "再生",
    mm: "ဖွင့်မည်"
  },
  pause_button: {
    en: "Pause",
    jp: "一時停止",
    mm: "ခေတ္တရပ်"
  },
  resume_button: {
    en: "Resume",
    jp: "再開",
    mm: "ပြန်စ"
  },
  vocab_test_btn: {
    en: "Start Test",
    jp: "テスト開始",
    mm: "စမ်းသပ်မည်"
  },
  vocab_test_desc: {
    en: "Practice words from this dialogue.",
    jp: "この対話の単語を練習します。",
    mm: "ဤသင်ခန်းစာမှ စာလုံးများကို လေ့ကျင့်ပါ။"
  },
  key_vocab_title: {
    en: "Key Vocabulary",
    jp: "重要単語",
    mm: "အဓိက ဝေါဟာရများ"
  },
  useful_phrases_title: {
    en: "Useful Phrases",
    jp: "便利なフレーズ",
    mm: "အသုံးဝင်သော စကားစုများ"
  },
  grammar_notes_title: {
    en: "Grammar Notes",
    jp: "文法ノート",
    mm: "သဒ္ဒါ မှတ်စုများ"
  },
  check_answers: {
    en: "Check Answers",
    jp: "答え合わせ",
    mm: "အဖြေတိုက်မည်"
  },
  reset_quiz: {
    en: "Reset Quiz",
    jp: "リセット",
    mm: "ပြန်ဖြေမည်"
  },
  show_translations: {
    en: "Show Translations",
    jp: "翻訳を表示",
    mm: "ဘာသာပြန်ကြည့်မည်"
  },
  hide_translations: {
    en: "Hide Translations",
    jp: "翻訳を隠す",
    mm: "ဘာသာပြန်ပိတ်မည်"
  },
  comprehension_check: {
    en: "Comprehension Check",
    jp: "理解度チェック",
    mm: "နားလည်မှု စစ်ဆေးခြင်း"
  },
  explanation_label: {
    en: "Explanation:",
    jp: "解説:",
    mm: "ရှင်းလင်းချက်:"
  },
  score_label: {
    en: "Score:",
    jp: "スコア:",
    mm: "အမှတ်:"
  },
  test_select_mode: {
    en: "Select Test Mode",
    jp: "テストモード選択",
    mm: "မေးခွန်းပုံစံ ရွေးချယ်ပါ"
  },
  test_back: {
    en: "Back to Practice",
    jp: "練習に戻る",
    mm: "လေ့ကျင့်ခန်းသို့ ပြန်သွားမည်"
  },
  test_retry: {
    en: "Retry Test",
    jp: "もう一度",
    mm: "ပြန်ဖြေမည်"
  },
  test_change_mode: {
    en: "Change Mode",
    jp: "モード変更",
    mm: "ပုံစံပြောင်းမည်"
  },
  test_exit: {
    en: "Exit to Review",
    jp: "終了して復習",
    mm: "ထွက်မည်"
  },
  test_question: {
    en: "Question",
    jp: "問",
    mm: "မေးခွန်း"
  },
  test_score: {
    en: "Score",
    jp: "点数",
    mm: "အမှတ်"
  },
  mode_kanji_hiragana: {
    en: "Kanji ➔ Hiragana",
    jp: "漢字 ➔ ひらがな",
    mm: "ခန်းဂျီး ➔ ဟီရာဂါးနား"
  },
  mode_hiragana_kanji: {
    en: "Hiragana ➔ Kanji",
    jp: "ひらがな ➔ 漢字",
    mm: "ဟီရာဂါးနား ➔ ခန်းဂျီး"
  },
  mode_hiragana_mm: {
    en: "Hiragana ➔ Meaning",
    jp: "ひらがな ➔ 意味",
    mm: "ဟီရာဂါးနား ➔ အဓိပ္ပါယ်"
  },
  mode_kanji_mm: {
    en: "Kanji ➔ Meaning",
    jp: "漢字 ➔ 意味",
    mm: "ခန်းဂျီး ➔ အဓိပ္ပါယ်"
  },
  test_result_perfect: {
    en: "Perfect! 🏆",
    jp: "完璧です！ 🏆",
    mm: "အရမ်းတော်ပါတယ်! 🏆"
  },
  test_result_great: {
    en: "Great Job! 🌟",
    jp: "素晴らしい！ 🌟",
    mm: "ဂုဏ်ယူပါတယ်! 🌟"
  },
  test_result_good: {
    en: "Good Effort! 👍",
    jp: "よく頑張りました！ 👍",
    mm: "ကြိုးစားမှုကောင်းပါတယ်! 👍"
  },
  test_result_keep_practicing: {
    en: "Keep Practicing!",
    jp: "練習を続けましょう！",
    mm: "ဆက်လက်ကြိုးစားပါ!"
  },
  custom_topic_placeholder: {
    en: "E.g., Returning a broken item at a shop",
    jp: "例：店で不良品を返品する",
    mm: "ဥပမာ - ဆိုင်တွင် ပျက်နေသောပစ္စည်း ပြန်လဲခြင်း"
  },
  footer_text: {
    en: "Japantag student",
    jp: "Japantag 生徒",
    mm: "Japantag ကျောင်းသား"
  },
  interview_field_label: {
    en: "Job Field",
    jp: "職種",
    mm: "အလုပ်အကိုင် ကဏ္ဍ"
  },
  interview_custom_placeholder: {
    en: "Enter specific job title or conditions (e.g., 'React Developer', 'Night Shift Nurse')...",
    jp: "具体的な職種や条件を入力してください（例：「React開発者」「夜勤看護師」）...",
    mm: "အလုပ်ရာထူးနှင့် အခြေအနေများကို အသေးစိတ်ရေးပါ (ဥပမာ - React Developer, ညဆိုင်း သူနာပြု)..."
  },
  field_engineer: { en: "Engineer", jp: "エンジニア", mm: "အင်ဂျင်နီယာ" },
  field_kaigo: { en: "Kaigo (Caregiving)", jp: "介護", mm: "သက်ကြီးရွယ်အို ပြုစုရေး (Kaigo)" },
  field_it: { en: "IT / Software", jp: "IT / ソフトウェア", mm: "IT / ဆော့ဖ်ဝဲ" },
  field_me: { en: "Mechanical Engineering (ME)", jp: "機械工学 (ME)", mm: "စက်မှုအင်ဂျင်နီယာ (ME)" },
  field_ec: { en: "Electronics/Comm (EC)", jp: "電子工学 (EC)", mm: "အီလက်ထရွန်းနစ် (EC)" },
  field_ep: { en: "Electrical Power (EP)", jp: "電力工学 (EP)", mm: "လျှပ်စစ်စွမ်းအား (EP)" },
  field_design: { en: "Design", jp: "デザイン", mm: "ဒီဇိုင်း" },
  field_other: { en: "Other / Custom", jp: "その他 / カスタム", mm: "အခြား / စိတ်ကြိုက်" },
  toggle_furigana: { en: "Furigana", jp: "ふりがな", mm: "Furigana" },
  theme_sakura: { en: "Sakura", jp: "桜", mm: "ချယ်ရီ" },
  theme_fuji: { en: "Mt. Fuji", jp: "富士山", mm: "ဖူဂျီတောင်" },
  theme_jinjya: { en: "Shrine", jp: "神社", mm: "ဂျပန်ဘုရားကျောင်း" },
  theme_beach: { en: "Beach", jp: "海", mm: "ကမ်းခြေ" },
  theme_sky: { en: "Sky", jp: "空", mm: "ကောင်းကင်" },
  theme_forest: { en: "Forest", jp: "森", mm: "သစ်တော" },
  theme_magic: { en: "Magic", jp: "魔法", mm: "မှော်" },
  theme_night: { en: "Night", jp: "夜空", mm: "ည" },
  theme_anime: { en: "Anime", jp: "アニメ", mm: "Anime" },
  theme_demon_slayer: { en: "Slayer", jp: "鬼殺隊", mm: "နတ်ဆိုးနှိမ်နင်းရေး" },
  theme_love: { en: "Love", jp: "愛", mm: "အချစ်" },
  theme_rain: { en: "Rain", jp: "雨", mm: "မိုး" },
  theme_three_d: { en: "3D World", jp: "3Dワールド", mm: "3D ကမ္ဘာ" },
  theme_fire: { en: "Fire", jp: "炎", mm: "မီး" },
  theme_hanabi: { en: "Hanabi", jp: "花火", mm: "မီးရှူးမီးပန်း" },
  theme_winter: { en: "Winter", jp: "冬", mm: "ဆောင်းရာသီ" },
  theme_one_piece: { en: "One Piece", jp: "ワンピース", mm: "One Piece" },
  theme_galaxy: { en: "Galaxy", jp: "銀河", mm: "ဂလက်ဆီ" },
  voice_settings: { en: "Audio Settings", jp: "音声設定", mm: "အသံချိန်ညှိမှု" },
  voice_speaker_a: { en: "Speaker A", jp: "話者 A", mm: "စကားပြောသူ A" },
  voice_speaker_b: { en: "Speaker B", jp: "話者 B", mm: "စကားပြောသူ B" },
  voice_speaker_c: { en: "Speaker C", jp: "話者 C", mm: "စကားပြောသူ C" },
  voice_narrator: { en: "Narrator", jp: "ナレーター", mm: "နောက်ခံစကားပြောသူ" },
  voice_male: { en: "Male", jp: "男性", mm: "ကျား" },
  voice_female: { en: "Female", jp: "女性", mm: "မ" },
  num_speakers: { en: "Characters", jp: "登場人物", mm: "ဇာတ်ကောင်အရေအတွက်" },
  speakers_1: { en: "1 (Monologue)", jp: "1人 (独白)", mm: "၁ ယောက် (တစ်ကိုယ်တော်)" },
  speakers_2: { en: "2 (Dialogue)", jp: "2人 (対話)", mm: "၂ ယောက် (အပြန်အလှန်)" },
  speakers_3: { en: "3 (Group)", jp: "3人 (会話)", mm: "၃ ယောက် (အဖွဲ့လိုက်)" },
  estimated_time: { en: "Estimated time", jp: "予想時間", mm: "ခန့်မှန်းချိန်" },
  seconds: { en: "sec", jp: "秒", mm: "စက္ကန့်" },
  calculating: { en: "Calculated based on complexity...", jp: "複雑度に基づいて計算中...", mm: "အခက်အခဲပေါ်မူတည်၍ တွက်ချက်နေသည်..." },
  voice_sharing_notice: {
    en: "Note: Speaker C will share the same voice as Speaker B because of AI limitation.",
    jp: "注意：AIの制限により、話者Cは話者Bと同じ音声を使用します。",
    mm: "သတိပြုရန် - AI ကန့်သတ်ချက်ကြောင့် စကားပြောသူ C သည် စကားပြောသူ B နှင့် အသံတူနေပါမည်။"
  }
};

export const t = (key: TranslationKey, lang: UILanguage): string => {
  return TRANSLATIONS[key]?.[lang] || TRANSLATIONS[key]?.['en'] || key;
};